### PR TITLE
Refactor controllers and extensions

### PR DESCRIPTION
**Pull request by GYFK**
I’ve added some changes to the project controllers and extensions.

1. Remove Objective-C association approach in adding activity indicator to UIButton as here we have no need in it.
2. Remove absolutely unneeded extensions, for ``trim``, ``content`` and ``root``. They were only used in a couple of places to substitute not so massive things itself. There is no need to do even a convenient extension for such tiny functionality.
I did also remove UIAlertControllers templates as the way of abstracting and constructing them was not expandable.
3. Fixed a number of typos and applied general refactoring due to the recent changes.

### CODE REVIEW

**Review by GreatAndPowerfulKing — CHANGES_REQUESTED** [review]
First of all, I would ask you to fix code indentation. As far, as I remember, we decided to use tabs. 

Also, I really don’t like new UIButton+ActivityIndicator implementation. Previous one was not perfect. Yeah, it used `ObjectiveC` API, which is not common in Swift, but such solution is universal and works properly in all cases. And the solution with searching for an appropriate background color and covering the entire button with it looks very strange. I suppose we should find better solution before merging or leave old solution.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing there was no such decision prior to this point about the code indentation. Yet as the changes were made to your group of controllers it is fair to change it to tabs. As for future changes I'd like to come up with a proper decision.

As for using Objective-C API, I would still recommend against using it as it will be possibly deprecated in the future, it is costly and I think there must be some better way to do it in a pure Swift. All in all , that is definitely not the place to use such approach so we can't rely on the present solution. As you can see, I have made a proper ``TODO`` label to change the suggested code in future. As for now, it covers 100% of its usage and should be kept until you come up with a better idea.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK I can't completely agree with you. It would be great to "do it in a pure Swift". But for now we don't have good solution in Swift yet. E. g. even if we will decide simply to add background image for our `ConnectionController` your implementation won't work properly.

And I suppose PR shouldn't contain such `TODO`'s and such strange and incomplete solutions.  So, while you can't replace existing solution with better one it would be better not to change it at all.

**Comment by GreatAndPowerfulKing** [comment]
Or, following your logic in other question, we can just remove this extension and write duplicating code in all places where we need such functionality, 'cause there are only two of them.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing as for now we are not supposed to add alterations to the UI. So either you suggest a better solution and make changes or we stick to the one in PR. It is still better, than to rely on the possibly deprecated api.

As for duplicating code that definitely is not right here as the implementation of the functionality is vast. In the other question we had rather tiny implementations.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK Currently you should provide better solution. As for now I have no idea how to improve you implementation. And `ObjectiveC` API is not deprecated for now, so we can use it. I'm against your new implementation. I suppose we should replace existing solution only when we will create good solution using "pure Swift".

**Comment by GYFK** [comment]
@GreatAndPowerfulKing the only two solutions I see then is to delete both variants and leave it blank or to subclass UIButton to infuse it with proper behavior.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK I think that while you can't provide better solution we should leave an existing one. Both solutions are less convenient than current.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing You did not also provide the proper the solution. So as far we both agree that there is no such one in project that should be kept.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK What else should I provide? As I've mentioned above, current solution perhaps is not perfect, but it's okay, using `ObjectiveC` is not illegal, deprecated etc. I suppose we should leave it.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing You should provide another solution, without using this API. According to you, we could use this mechanism to make stored variables in mostly every extension. I agree that sometimes we do need to use this mechanism. Yet such use cases are rare.They do not include just adding a subview to UIButton. That is not a good approach. If you have no better idea, provide an UIButton subclass with proper behavior.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing besides, your solution has a significant flaw. When you add another subview to the UIButton and add some constraints to the superview that reference this subview, after you use ``removeFromSuperview()`` all that constraints get wiped. When you restore subviews from ``cachedSubviews`` you have no constraints to that items. 

My solution does not modify the hierarchy however. It basically does work properly only in simple cases (which, as I mentioned, covers 100% of current usage) and should be substituted with the better solution. But it is less harmful than current.

**Comment by GreatAndPowerfulKing** [comment]
@GYFK We also don't add some additional subviews with constraints. And simple cases are much more common.

**Comment by GreatAndPowerfulKing** [comment]
Also, okay, I'll work on a better solution using "pure Swift" and will make a PR as far as it will be possible. But for now I propose to leave current solution.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing the objection is that both solutions are bad but in the cases that are not present in a project? Not a good one. I suggest to merge the current PR and as soon as you come with the better approach create a new one. And to close the discussion until then.

**Comment by GreatAndPowerfulKing** [comment]
I don't think so, 'cause there is no sense to merge something bad into `master` with confidence that it will be replaced soon.

**Comment by GYFK** [comment]
@GreatAndPowerfulKing  LGTM

**Review by GreatAndPowerfulKing — APPROVED** [review]

**Pull request merged**
